### ISSUE TITLE
Wayland: could not get next buffer

### ISSUE THREAD

**Issue by dibusure** [Cloudef/bemenu#259] opened 2022-05-04 15:35 UTC
Today i installed gentoo with sway. I try to launch bemenu and it launched, but before a few seconds it "crashed" ( stopped ) with error "could not get next buffer". Any help?

**Comment by astralchan** [comment] 2022-09-05 02:50
I am experiencing same issue on `gentoo-musl` using `sway`. It seems to occasionally crash when typing. It's rather random when it crashes - other than it's always when typing. One thing I can do to make it crash consistently is to pipe a big file into it - e.g. `cat BIGFILE | bemenu -i -l 30`. Typing at all will crash it every time consistently with "`could not get next buffer`." Even when not typing - scrolling too fast with the arrow keys will consistently crash bemenu with the same error. This error occurs with `dev-libs/bemenu-0.3.6-r2`.
However, that ebuild is quite behind. The latest release is [`0.6.10`](https://github.com/Cloudef/bemenu/releases/tag/0.6.10). After building and running - `LD_LIBRARY_PATH=. BEMENU_RENDERERS=. ./bemenu-run`, the issue is no longer there.
Which version of `bemenu` are you using on gentoo (e.g. `eix bemenu`).

**Comment by astralchan** [comment] 2022-09-07 00:49
The [ebuild for bemenu](https://packages.gentoo.org/packages/dev-libs/bemenu) was recently updated to version `0.6.10`. This is now fixed on my end. Try syncing and updating your world set - it should be fixed now.

**Closed** 2024-07-19 04:02 UTC
