### ISSUE TITLE
Keypresses register on release (Wayland)

### ISSUE THREAD

**Issue by and-nissa** [Cloudef/bemenu#275] opened 2022-07-01 16:03 UTC
**Info**

Wayland backend, currently running bemenu v0.6.8             

**Issue**

Between 0.6.7 and 0.6.8, keypresses have changed from registering on initial press (0.6.7) to on release (0.6.8).

I didn't change any configuration between updates, so I'm thinking it's a bug.

**Comment by CameronNemo** [comment] 2022-07-03 20:07
I am noticing something weird with keyboard input on Wayland too.

**Comment by joanbm** [comment] 2022-07-05 01:07
I can reproduce the issue and it has the same root cause as #274, in some cases the menu was not being rendered until a further event happened. In this case the key press event did not cause a render when it should have, and the render didn't happen until the next event, most likely the key release.

Should be fixed by #279.

**Closed** 2022-07-05 01:06 UTC
