### ISSUE TITLE
Rendering/Display issue when upgrading to 0.4.1

### ISSUE THREAD

**Issue by chrisvittal** [Cloudef/bemenu#117] opened 2020-05-07 15:08 UTC
System: Archlinux, bemenu and bemenu-wlroots installed from the official repositories. Sway window manager.

I invoke bemenu with `dmenu_path | -l15 -p '>>>' -P ' ->' `, along with some color/font configuration. I have tested this after removing the color/font configuration and have found my issue not resolved.

After upgrading, I see the following.
![grim_2020-05-07T10:59:29-0400](https://user-images.githubusercontent.com/15916123/81310814-99300300-9052-11ea-8e2e-91568904ac5a.png)
Note the black intrusion into the prompt and gap behind in rendering on selected line. Also, the prompt and the selection indicator used to line up, but no longer do.

Before upgrading, I saw the following:
![grim_2020-05-07T11:01:52-0400](https://user-images.githubusercontent.com/15916123/81311097-f75ce600-9052-11ea-8fe0-5b67f027a9c2.png)

Other than pinning to the old version, how can I restore the behavior?

Thank you very much for the great program.

**Comment by ggreer** [comment] 2020-05-08 05:17
I have the same issue. I'm on 0.4.0-1 of both bemenu and bemenu-wlroots using sway version 1.4-9cda5a5b (May  8 2020, branch 'master').

![Screenshot from 2020-05-07 22-07-23](https://user-images.githubusercontent.com/200121/81372460-459fd280-90af-11ea-9c78-1895225817ad.png)

This only seems to happen in vertical layout mode (`-l 8` or any number). Also the height of the dark rectangle on the left seems to be proportional to the number of lines. eg: It's shorter if I use `-l 2` and taller if I use `-l 20`.

**Comment by Cloudef** [comment] 2020-05-08 09:16
I can't seem to be able to reproduce this under X11 at least.

**Comment by Cloudef** [comment] 2020-05-08 09:41
Can you check if the transpareny support caused these artifacts? https://github.com/Cloudef/bemenu/commit/6350a4000dcb89203ed7d7ad8398424b930541aa 

If you can bisect the problematic commit that would help.

**Comment by chrisvittal** [comment] 2020-05-08 12:10
Okay, bisected. Transparency doesn't seem to be the issue. The issue seems mostly to be related to the scrollbar. The two commits where I begin to see issues are:

bb7db3e cairo/curses: dmenu like indent for lists
1c487ba cairo: make scrollbar 1 character thick

In 1c487ba, I can see the scrollbar push the selection prompt to the right and intrude on the input prompt.
![grim_2020-05-08T07:49:11-0400](https://user-images.githubusercontent.com/15916123/81404178-e8357100-9102-11ea-8ead-55a836b46680.png)
In bb7db3e, I see the problematic behavior
![grim_2020-05-08T07:56:02-0400](https://user-images.githubusercontent.com/15916123/81404211-f71c2380-9102-11ea-96d5-964774ad1bbc.png)

**Comment by Cloudef** [comment] 2020-06-24 07:08
I'll check this out this weekend and draft new release after fixed.

**Comment by Cloudef** [comment] 2020-06-28 14:22
Interestingly I can't seem to reproduce this on sway. But I think I'll know what's wrong so I probably can reproduce this effect by modifying the code a bit.

**Comment by Cloudef** [comment] 2020-06-28 14:31
Nevermind, my guess didn't seem to be right. Is there some other variables in play here? Are you doing hidpi rendering for example?

**Comment by chrisvittal** [comment] 2020-06-28 14:44
Yes. I'm working with 2x scaling on a 4k display.

**Comment by Cloudef** [comment] 2020-06-28 15:14
https://github.com/Cloudef/bemenu/commit/7266ebb795e6290440c082c41d3ef3e271c2470c should be fixed by this. Can you confirm? Also as a bonus latest commit includes BEMENU_SCALE env variable that can be used to set bemenu specific  scale factor that overrides any system one. (works on x11 too)

**Comment by chrisvittal** [comment] 2020-06-28 16:03
Confirmed fixed! Thank you so much!

**Comment by Cloudef** [comment] 2020-06-28 16:06
I'll sprung up new release then tomorrow.

**Comment by Cloudef** [comment] 2020-07-04 09:14
Delayed a bit, but fixed now in 0.5.0 release.

**Closed by Cloudef** 2020-07-04 09:14 UTC
Labels: wayland, x11
